### ISSUE TITLE
Support Folder Organization

### ISSUE THREAD

**Issue by JDRanpariya** [willbchang/chrome-read-later#180]
**Is your feature request related to a problem? Please describe.**
Problem: I don't want to clutter up everything in one list like articles, videos, courses etc.in different domains like webdev, data science etc.
The problem with chrome bookmarks is I need to open site to bookmark. but I want to right click then select folder, or add folder and save bookmark

**Describe the solution you'd like**
Basically support folders on right click.
![](http://www.rawinfopages.com/tips/wp-content/uploads/2017/08/chrome-bookmarks2.png)

**Describe alternatives you've considered**
Alternatives I've tried are Instapaper. but the problem is it doesn't support nested folders. I've also tried right click bookmark extension but it also doesn't support folders.

### You sound like cool guy. article progress is shown which blew my mind. If you think I can help in anyway please tell me I am ready to put efforts to get this working. I Appreciate the hard work you guys have put in this project.

**Comment by willbchang** [comment]
Hi @JDRanpariya, thanks for your feedback and encouragement!

Personally, I don't save everything to Chrome's bookmarks. My methodology for Chrome's bookmarks is that only saves websites like tools/blogs/news/etc, these items are kind of persistent and do not change often. It would be painful to save and delete the bookmark items frequently, bookmarks can be massive and hard to manage after a white if we don't do that.

So that's why I created Chrome Read Later as a temporary bookmark, easy to save and delete items. It is suitable for websites like a specific blog post you're reading and want to read later, or a learning page in an education website and you want to continue later on.

I agree with you that things are a little bit messed up right now, although it's a temporary bookmark. I had thoughts about classifying things with their own topic but haven't got an easy-to-use   solution. Please let me know if you have any idea.

Currently for your request, you can use things like this: [Save to folder from context menu](https://chrome.google.com/webstore/detail/save-to-folder-from-conte/pdlkjdlbjjfmlfhijdbdpkilpdoncgdk?hl=en) or check others [chrome extension save link to folder]https://www.google.com/search?q=chrome+extension+save+link+to+folder).

**Comment by JDRanpariya** [comment]
I tried it, I don't think It's working properly. Idea would be to have kind of dialog chrome bookmark provides when you bookmark certain page. I don't have any idea on how to implement it. But I will trying figuring it out. Once I get to know something I will update you.
