### ISSUE TITLE
[FEAT] Drop URL on icon

### ISSUE THREAD

**Issue by GeoNomad** [willbchang/chrome-read-later#214]
I don't know if this is really easy or really hard.

I would like to be able to drag a link from  a web page and drop it on the icon in the Bookmark Bar to add it to the read later list.

This would replicate a functionality I have used for many years with a Windows App of mine that I have used as a read later list for the past 25 years or so.

**Comment by willbchang** [comment]
Good idea! After some digging I found that popup only has [onClicked](https://developer.chrome.com/docs/extensions/reference/action/#event-onClicked) event which cannot finish this feature. Please let me know if you have experienced this behavior in other extensions, so I can look into their code and learn how to achieve it.

Currently, you can save link to Read Later by **right clicking the link** and choose **Save to Read Later**, otherwise it will save current tab.

<img width="514" alt="Screen Shot 2022-03-26 at 11 23 12" src="https://user-images.githubusercontent.com/14329786/160222967-ae64c15a-fa2d-41b9-ada7-87095c5e124e.png">

In the future, I want to engage Read Later with [Vimum like](https://github.com/gdh1995/vimium-c) extension, to make `s` save link on page, like the `f`.
<img width="1628" alt="Screen Shot 2022-03-26 at 11 27 25" src="https://user-images.githubusercontent.com/14329786/160223059-aa7840b4-3ea7-4c99-8a05-e6f5d646b280.png">

**Comment by GeoNomad** [comment]
Yes, I use the right-click almost exclusively right now.

The drag-drop is in my muscle memory from having had the feature for so long in my private app for reading later on Windows.

I have not been able to find an event for drop on the icon either, so I was just hoping you might have found something. Does click fire when dropping? Probably not, because the mouse down is elsewhere. Mouse up? Or even hover over the icon. Something to look at.

**Comment by willbchang** [comment]
Maybe: 
- Writing some functions in content-script to make the drag-drop behavior inside current page instead of the extension icon, e.g. shows up a Read Later icon in the **top right corner** or **nearby the cursor** when there is a dragging event. 
- [Implementing a new extension API](https://www.chromium.org/developers/design-documents/extensions/proposed-changes/creating-new-apis/) to maintain a personal use chrome.
- [Making a New Extension API Proposal](https://chromium.googlesource.com/chromium/src/+/HEAD/extensions/docs/new_api_proposal.md) to make it happen if they accept the proposal.

The first way is easier in my opinion, I hope the suggestions can help you in some way.
