### ISSUE TITLE
[BUG] unable to delete links

### ISSUE THREAD

**Issue by glebarr** [willbchang/chrome-read-later#223]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by willbchang** [comment]
@glebarr Thanks for your feedback. I'll investigate this bug and fix it asap.

**Comment by willbchang** [comment]
@glebarr This issue has been fixed. I'll make a new release in chrome web store today so that users can get this fix in a day or two.

REASON: The process that pushes the deleted url to db is terminated by `window.close()` sometimes.
SOLUTION: Send the deleted url to the background and then push the url to the db.

**Comment by glebarr** [comment]
cool thanks
